/**
 * Slug de região -> nome de exibição ("centralus" -> "Central US").
 *
 * O portal usa o nome de exibição no parâmetro `location` da WorkflowMenuBlade,
 * enquanto o ARM e o Resource Graph devolvem o slug. Não há regra derivável:
 * "japaneast" vira "Japan East", mas "centralus" vira "Central US" — a posição
 * da direção muda conforme a região. Tentar deduzir acertou 50 de 109.
 *
 * Gerado a partir de `az account list-locations` em 26/08/2026. Regiões novas
 * caem no fallback de `regionDisplayName`, que devolve o slug — o portal ainda
 * abre, só sem o nome bonito.
 */
export const REGION_DISPLAY_NAMES: Readonly<Record<string, string>> = {
  asia: 'Asia',
  asiapacific: 'Asia Pacific',
  australia: 'Australia',
  australiacentral: 'Australia Central',
  australiacentral2: 'Australia Central 2',
  australiaeast: 'Australia East',
  australiasoutheast: 'Australia Southeast',
  austria: 'Austria',
  austriaeast: 'Austria East',
  belgium: 'Belgium',
  belgiumcentral: 'Belgium Central',
  brazil: 'Brazil',
  brazilsouth: 'Brazil South',
  brazilsoutheast: 'Brazil Southeast',
  canada: 'Canada',
  canadacentral: 'Canada Central',
  canadaeast: 'Canada East',
  centralindia: 'Central India',
  centralus: 'Central US',
  centraluseuap: 'Central US EUAP',
  centralusstage: 'Central US (Stage)',
  chile: 'Chile',
  chilecentral: 'Chile Central',
  denmark: 'Denmark',
  denmarkeast: 'Denmark East',
  eastasia: 'East Asia',
  eastasiastage: 'East Asia (Stage)',
  eastus: 'East US',
  eastus2: 'East US 2',
  eastus2euap: 'East US 2 EUAP',
  eastus2stage: 'East US 2 (Stage)',
  eastusstage: 'East US (Stage)',
  eastusstg: 'East US STG',
  europe: 'Europe',
  finland: 'Finland',
  france: 'France',
  francecentral: 'France Central',
  francesouth: 'France South',
  germany: 'Germany',
  germanynorth: 'Germany North',
  germanywestcentral: 'Germany West Central',
  global: 'Global',
  india: 'India',
  indiasouthcentral: 'India South Central',
  indonesia: 'Indonesia',
  indonesiacentral: 'Indonesia Central',
  israel: 'Israel',
  israelcentral: 'Israel Central',
  italy: 'Italy',
  italynorth: 'Italy North',
  japan: 'Japan',
  japaneast: 'Japan East',
  japanwest: 'Japan West',
  jioindiacentral: 'Jio India Central',
  jioindiawest: 'Jio India West',
  korea: 'Korea',
  koreacentral: 'Korea Central',
  koreasouth: 'Korea South',
  malaysia: 'Malaysia',
  malaysiawest: 'Malaysia West',
  mexico: 'Mexico',
  mexicocentral: 'Mexico Central',
  newzealand: 'New Zealand',
  newzealandnorth: 'New Zealand North',
  northcentralus: 'North Central US',
  northcentralusstage: 'North Central US (Stage)',
  northeurope: 'North Europe',
  norway: 'Norway',
  norwayeast: 'Norway East',
  norwaywest: 'Norway West',
  poland: 'Poland',
  polandcentral: 'Poland Central',
  qatar: 'Qatar',
  qatarcentral: 'Qatar Central',
  saudiarabia: 'Saudi Arabia',
  singapore: 'Singapore',
  southafrica: 'South Africa',
  southafricanorth: 'South Africa North',
  southafricawest: 'South Africa West',
  southcentralus: 'South Central US',
  southcentralusstage: 'South Central US (Stage)',
  southcentralusstg: 'South Central US STG',
  southeastasia: 'Southeast Asia',
  southeastasiastage: 'Southeast Asia (Stage)',
  southindia: 'South India',
  spain: 'Spain',
  spaincentral: 'Spain Central',
  sweden: 'Sweden',
  swedencentral: 'Sweden Central',
  switzerland: 'Switzerland',
  switzerlandnorth: 'Switzerland North',
  switzerlandwest: 'Switzerland West',
  taiwan: 'Taiwan',
  uae: 'United Arab Emirates',
  uaecentral: 'UAE Central',
  uaenorth: 'UAE North',
  uk: 'United Kingdom',
  uksouth: 'UK South',
  ukwest: 'UK West',
  unitedstates: 'United States',
  unitedstateseuap: 'United States EUAP',
  westcentralus: 'West Central US',
  westeurope: 'West Europe',
  westindia: 'West India',
  westus: 'West US',
  westus2: 'West US 2',
  westus2stage: 'West US 2 (Stage)',
  westus3: 'West US 3',
  westusstage: 'West US (Stage)',
}

/** Nome de exibição da região, ou o próprio slug quando desconhecida. */
export function regionDisplayName(slug: string): string {
  return REGION_DISPLAY_NAMES[slug.toLowerCase()] ?? slug
}
